const $ = (id) => document.getElementById(id);
const strings = {
  tr:{subtitle:"Bir fotoğraf çek. Gördüğünün ardındaki düzeni düşün.",pickLabel:"Fotoğraf çek veya seç",pickHint:"Kamera, galeri veya dosyalar",analyze:"Üzerinde düşün",privacy:"Fotoğraf yalnızca analiz için güvenli sunucuya gönderilir.",loading:"Fotoğraf inceleniyor…",science:"Bilim",reflection:"Tefekkür",quran:"Kur’an’dan bir işaret",seen:"GÖRDÜĞÜN",again:"Başka bir fotoğraf seç",error:"Analiz yapılamadı. Lütfen tekrar dene."},
  en:{subtitle:"Take a photo. Reflect on the order behind what you see.",pickLabel:"Take or choose a photo",pickHint:"Camera, gallery or files",analyze:"Reflect on it",privacy:"The photo is sent securely only for analysis.",loading:"Examining the image…",science:"Science",reflection:"Reflection",quran:"A sign from the Qur’an",seen:"WHAT YOU SEE",again:"Choose another photo",error:"The analysis failed. Please try again."},
  de:{subtitle:"Mach ein Foto. Denke über die Ordnung hinter dem Sichtbaren nach.",pickLabel:"Foto aufnehmen oder auswählen",pickHint:"Kamera, Galerie oder Dateien",analyze:"Darüber nachdenken",privacy:"Das Foto wird nur zur Analyse sicher übertragen.",loading:"Das Bild wird untersucht…",science:"Wissenschaft",reflection:"Nachdenken",quran:"Ein Zeichen aus dem Qur’an",seen:"WAS DU SIEHST",again:"Anderes Foto auswählen",error:"Die Analyse ist fehlgeschlagen. Bitte versuche es erneut."}
};
let imageData = "";
function applyLanguage(){const s=strings[$("language").value];$("subtitle").textContent=s.subtitle;$("pickLabel").textContent=s.pickLabel;$("pickHint").textContent=s.pickHint;$("analyzeBtn").textContent=s.analyze;$("privacy").textContent=s.privacy;$("scienceLabel").textContent=s.science;$("reflectionLabel").textContent=s.reflection;$("quranLabel").textContent=s.quran;$("resultLabel").textContent=s.seen;$("againBtn").textContent=s.again;}
$("language").addEventListener("change",applyLanguage);
$("imageInput").addEventListener("change",async(e)=>{const file=e.target.files?.[0];if(!file)return;imageData=await resizeImage(file);$("preview").src=imageData;$("preview").hidden=false;$("analyzeBtn").disabled=false;$("result").hidden=true;});
$("analyzeBtn").addEventListener("click",async()=>{const s=strings[$("language").value];$("status").hidden=false;$("status").textContent=s.loading;$("analyzeBtn").disabled=true;$("result").hidden=true;try{const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image:imageData,language:$("language").value})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Request failed");render(data);$("status").hidden=true;}catch(err){console.error(err);$("status").textContent=s.error;}finally{$("analyzeBtn").disabled=false;}});
$("againBtn").addEventListener("click",()=>{$("imageInput").click();});
function render(d){$("title").textContent=d.title;$("observation").textContent=d.observation;$("science").textContent=d.science;$("reflection").textContent=d.reflection;$("question").textContent=d.question;if(d.quran_reference||d.quran_text){$("quranText").textContent=d.quran_text;$("quranReference").textContent=d.quran_reference;$("quranCard").hidden=false;}else{$("quranCard").hidden=true;}$("result").hidden=false;$("result").scrollIntoView({behavior:"smooth",block:"start"});}
function resizeImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1400;let w=img.width,h=img.height;if(Math.max(w,h)>max){const scale=max/Math.max(w,h);w=Math.round(w*scale);h=Math.round(h*scale);}const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.getContext("2d").drawImage(img,0,0,w,h);resolve(canvas.toDataURL("image/jpeg",.82));};img.src=reader.result;};reader.readAsDataURL(file);});}
applyLanguage();
